on:
  push:
    paths:
      - terraform/**

jobs:
  print-env:
    name: Set env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print folder name
        working-directory: ./terraform
        run: |
          git diff --name-only "HEAD^" "HEAD"
